from fastapi import APIRouter, Query, HTTPException
from typing import List, Optional
from ..models import LogsResponse, LogEntry
from ..services.log_simulator import simulator
from ..utils.helpers import generate_id

router = APIRouter(prefix="/logs", tags=["Log Management"])

# In-memory store for generated logs (for demo persistence)
log_store = []
MAX_STORED_LOGS = 200

@router.get("/", response_model=LogsResponse)
async def get_logs(
    limit: int = Query(50, ge=1, le=200, description="Number of logs to return"),
    service: Optional[str] = Query(None, description="Filter by service name"),
    level: Optional[str] = Query(None, description="Filter by log level (INFO, WARNING, ERROR)")
):
    """
    Get recent logs from the simulated infrastructure.
    Returns logs generated by the log simulator.
    """
    try:
        # Get logs from global store, or generate fresh batch if store empty
        global log_store
        if not log_store:
            # Generate initial batch of logs
            log_store = simulator.generate_log_batch(30)
        
        # Filter logs
        filtered_logs = log_store.copy()
        
        if service:
            filtered_logs = [log for log in filtered_logs if log.service.value == service]
        
        if level:
            filtered_logs = [log for log in filtered_logs if log.level == level.upper()]
        
        # Sort by timestamp (newest first for display)
        filtered_logs.sort(key=lambda x: x.timestamp, reverse=True)
        
        # Apply limit
        result_logs = filtered_logs[:limit]
        
        return LogsResponse(
            success=True,
            logs=result_logs,
            count=len(result_logs),
            error=None
        )
        
    except Exception as e:
        return LogsResponse(
            success=False,
            logs=[],
            count=0,
            error=f"Failed to retrieve logs: {str(e)}"
        )

@router.post("/generate")
async def generate_logs(count: int = Query(5, ge=1, le=50)):
    """
    Generate a new batch of logs and append to the store.
    Use this to simulate real-time log ingestion.
    """
    global log_store
    new_logs = simulator.generate_log_batch(count)
    log_store.extend(new_logs)
    
    # Trim store if exceeds max
    if len(log_store) > MAX_STORED_LOGS:
        log_store = log_store[-MAX_STORED_LOGS:]
    
    return {
        "success": True,
        "generated": len(new_logs),
        "total_stored": len(log_store)
    }

@router.post("/trigger-incident")
async def trigger_incident(
    incident_type: str = Query(..., description="Type of incident: db_connection_exhaustion, payment_timeout, redis_memory_exhaustion"),
    duration: int = Query(10, ge=2, le=60, description="Duration in seconds")
):
    """
    Trigger a simulated incident. While active, logs will contain errors/warnings.
    """
    valid_types = ["db_connection_exhaustion", "payment_timeout", "redis_memory_exhaustion"]
    if incident_type not in valid_types:
        raise HTTPException(status_code=400, detail=f"Invalid incident_type. Choose from: {valid_types}")
    
    simulator.trigger_incident(incident_type, duration)
    
    return {
        "success": True,
        "message": f"Incident '{incident_type}' triggered for {duration} seconds",
        "incident_info": simulator.get_incident_info()
    }

@router.get("/incident-status")
async def get_incident_status():
    """Get current incident status (active or not, affected services)."""
    return simulator.get_incident_info()

@router.post("/clear")
async def clear_logs():
    """Clear all stored logs (useful for resetting demo)."""
    global log_store
    log_store = []
    return {"success": True, "message": "All logs cleared"}